###Agent Get All
GET http://localhost:8080/api/agent

###Agent Get
GET http://localhost:8080/api/agent/6

###Agent Add
POST http://localhost:8080/api/agent
Content-Type: application/json

{
    "firstName":"Warren",
    "middleName": "C",
    "lastName":"Longmire",
    "dob":"1999-09-09",
    "heightInInches": 59   
}